blank_issues_enabled: true
contact_links:
  - name: FederationCoin
    url: https://federationcoin.org
    about: Project site
  - name: FederationCoin issues
    url: https://github.com/FederationCoin/FederationCoin/issues
    about: Node software issues
