#!/usr/bin/env bash
#
#  federationcoind The FederationCoin server.
#
#
# chkconfig: 345 80 20
# description: federationcoind
# processname: federationcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/federationcoind, see below
if [ -f /etc/sysconfig/federationcoind ]; then
        . /etc/sysconfig/federationcoind
fi

RETVAL=0

prog=federationcoind
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/federationcoind
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/federationcoind}

# federationcoind defaults to /usr/bin/federationcoind, override with BITCOIND_BIN
federationcoind=${BITCOIND_BIN-/usr/bin/federationcoind}

# federationcoind opts default to -disablewallet, override with BITCOIND_OPTS
federationcoind_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $federationcoind $federationcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
